import { Conversation } from '@/types';

export const CONVERSATIONS: Conversation[] = [
  {
    id: 'conv-1',
    contact: {
      id: 1,
      firstName: 'Olivia',
      lastName: 'Mckinsey',
      name: 'Olivia Mckinsey',
      email: 'olivia.Mckinsey@gmail.com',
      phone: '+1 (312) 555-0134',
      initials: 'O',
      avatarColor: '#a855f7', // Purple matching screenshot
      assignee: 'James West',
      team: 'Sales Team',
    },
    lastMessage: 'Oh my god 🤩 I\'ll try it ASAP, thank..',
    timestamp: '23:23',
    unreadCount: 0,
    status: 'open',
    category: 'my_inbox',
    team: 'sales',
    labels: ['Closed Won', 'Chicago'],
    notes: ['Strong potential for future upgrades'],
    messages: [
      {
        id: 'm1',
        senderId: 1,
        senderName: 'Olivia Mckinsey',
        text: "Hi, I recently joined Fit4Life and I'm trying to access my workout plan, but I can't login. Can you help?",
        timestamp: '23:08',
        isMe: false,
      },
      {
        id: 'm2',
        senderId: 'me',
        senderName: 'Michael Johnson',
        text: "Hello Olivia 👋 I'm Michael, your AI customer support assistant. Let's fix this quickly. Could you confirm the email address?",
        timestamp: '23:08',
        isMe: true,
        status: 'read',
      },
      {
        id: 'm3',
        senderId: 1,
        senderName: 'Olivia Mckinsey',
        text: "Yes, it's olivia.Mckinsey@gmail.com",
        timestamp: '23:16',
        isMe: false,
      },
      {
        id: 'm4',
        senderId: 'me',
        senderName: 'Michael Johnson',
        text: "Thanks! Looks like your reset wasn't completed. I've sent a new link - please check your inbox.",
        timestamp: '23:16',
        isMe: true,
        status: 'read',
      },
      {
        id: 'm5',
        senderId: 1,
        senderName: 'Olivia Mckinsey',
        text: 'I see it. resetting now...',
        timestamp: '23:17',
        isMe: false,
      },
      {
        id: 'm6',
        senderId: 1,
        senderName: 'Olivia Mckinsey',
        text: "Done! I'm logged in. Thanks!",
        timestamp: '23:20',
        isMe: false,
      },
      {
        id: 'm7',
        senderId: 'me',
        senderName: 'Michael Johnson',
        text: '🎉 Perfect! Your plan is ready under “My Programs”. Since you\'re starting out, I suggest our Premium Guide - it boosts results and is 20% off here 👉 www.Fit4Life.com/Premium',
        timestamp: '23:20',
        isMe: true,
        status: 'read',
      },
      {
        id: 'm8',
        senderId: 1,
        senderName: 'Olivia Mckinsey',
        text: 'Oh my god 🤩 I\'ll try it ASAP, thank you so much!!',
        timestamp: '23:23',
        isMe: false,
      },
    ],
  },
  {
    id: 'conv-2',
    contact: {
      id: 2,
      firstName: 'Sara',
      lastName: 'Williams',
      name: 'Sara Williams',
      email: 'sara.williams@techcorp.io',
      phone: '+1 (415) 892-4110',
      initials: 'E',
      avatarColor: '#f59e0b', // Amber yellow matching screenshot
      assignee: 'James West',
      team: 'Sales Team',
    },
    lastMessage: 'Good Evening, Emily! Hope you are..',
    timestamp: '23:16',
    unreadCount: 0,
    status: 'open',
    category: 'my_inbox',
    team: 'sales',
    labels: ['Enterprise'],
    notes: [],
    messages: [
      {
        id: 's1',
        senderId: 2,
        senderName: 'Sara Williams',
        text: 'Good Evening, Emily! Hope you are doing well.',
        timestamp: '23:16',
        isMe: false,
      },
    ],
  },
  {
    id: 'conv-3',
    contact: {
      id: 3,
      firstName: 'Frank',
      lastName: 'Thompson',
      name: 'Frank Thompson',
      email: 'frank.t@designstudio.co',
      phone: '+1 (312) 441-9820',
      initials: 'F',
      avatarColor: '#3b82f6', // Blue matching screenshot
      assignee: 'Unassigned',
      team: 'Customer Support',
    },
    lastMessage: 'Thank you for signing up Frank! If t..',
    timestamp: '22:28',
    unreadCount: 0,
    status: 'open',
    category: 'all',
    team: 'customer_support',
    labels: ['Onboarding'],
    notes: [],
    messages: [
      {
        id: 'f1',
        senderId: 3,
        senderName: 'Frank Thompson',
        text: 'Thank you for signing up Frank! If there is anything you need help with please let us know.',
        timestamp: '22:28',
        isMe: false,
      },
    ],
  },
  {
    id: 'conv-4',
    contact: {
      id: 4,
      firstName: 'Grace',
      lastName: 'Lee',
      name: 'Grace Lee',
      email: 'grace.lee@innovate.org',
      phone: '+1 (206) 774-1290',
      initials: 'G',
      avatarColor: '#f97316', // Orange matching screenshot
      assignee: 'Sarah Connor',
      team: 'Customer Support',
    },
    lastMessage: 'I am sending you the report right a..',
    timestamp: '20:43',
    unreadCount: 0,
    status: 'open',
    category: 'all',
    team: 'customer_support',
    labels: [],
    notes: [],
    messages: [
      {
        id: 'g1',
        senderId: 4,
        senderName: 'Grace Lee',
        text: 'I am sending you the report right away.',
        timestamp: '20:43',
        isMe: false,
      },
    ],
  },
  {
    id: 'conv-5',
    contact: {
      id: 5,
      firstName: 'Henry',
      lastName: 'Adams',
      name: 'Henry Adams',
      email: 'henry.adams@venture.com',
      phone: '+1 (650) 332-9011',
      initials: 'H',
      avatarColor: '#eab308', // Yellow matching screenshot
      assignee: 'James West',
      team: 'Sales Team',
    },
    lastMessage: 'Thank you for filling out our survey!',
    timestamp: '17:37',
    unreadCount: 0,
    status: 'open',
    category: 'my_inbox',
    team: 'sales',
    labels: [],
    notes: [],
    messages: [
      {
        id: 'h1',
        senderId: 5,
        senderName: 'Henry Adams',
        text: 'Thank you for filling out our survey!',
        timestamp: '17:37',
        isMe: false,
      },
    ],
  },
  {
    id: 'conv-6',
    contact: {
      id: 6,
      firstName: 'Isabella',
      lastName: 'Martinez',
      name: 'Isabella Martinez',
      email: 'isabella.m@partner.io',
      phone: '+1 (202) 455-1900',
      initials: 'I',
      avatarColor: '#f97316', // Orange matching screenshot
      assignee: 'James West',
      team: 'Sales Team',
    },
    lastMessage: 'I will update you soon Isabella!',
    timestamp: '16:01',
    unreadCount: 0,
    status: 'open',
    category: 'my_inbox',
    team: 'sales',
    labels: [],
    notes: [],
    messages: [
      {
        id: 'i1',
        senderId: 6,
        senderName: 'Isabella Martinez',
        text: 'I will update you soon Isabella!',
        timestamp: '16:01',
        isMe: false,
      },
    ],
  },
  {
    id: 'conv-7',
    contact: {
      id: 7,
      firstName: 'James',
      lastName: 'Brown',
      name: 'James Brown',
      email: 'james.brown@corp.io',
      phone: '+1 (312) 788-2200',
      initials: 'J',
      avatarColor: '#8b5cf6', // Purple matching screenshot
      assignee: 'Unassigned',
      team: 'Customer Support',
    },
    lastMessage: 'Hello James! Let\'s collaborate on..',
    timestamp: '13:44',
    unreadCount: 0,
    status: 'open',
    category: 'all',
    team: 'customer_support',
    labels: [],
    notes: [],
    messages: [
      {
        id: 'j1',
        senderId: 7,
        senderName: 'James Brown',
        text: "Hello James! Let's collaborate on the upcoming project.",
        timestamp: '13:44',
        isMe: false,
      },
    ],
  },
  {
    id: 'conv-8',
    contact: {
      id: 8,
      firstName: 'Katherine',
      lastName: 'White',
      name: 'Katherine White',
      email: 'katherine.w@startup.co',
      phone: '+1 (347) 600-7890',
      initials: 'K',
      avatarColor: '#eab308', // Yellow matching screenshot
      assignee: 'Unassigned',
      team: 'Customer Support',
    },
    lastMessage: 'Hi Katherine, looking forward to our..',
    timestamp: '09:02',
    unreadCount: 0,
    status: 'open',
    category: 'unassigned',
    team: 'customer_support',
    labels: [],
    notes: [],
    messages: [
      {
        id: 'k1',
        senderId: 8,
        senderName: 'Katherine White',
        text: 'Hi Katherine, looking forward to our next meeting!',
        timestamp: '09:02',
        isMe: false,
      },
    ],
  },
  {
    id: 'conv-9',
    contact: {
      id: 9,
      firstName: 'Lucas',
      lastName: 'Green',
      name: 'Lucas Green',
      email: 'lucas.green@media.co',
      phone: '+1 (415) 321-5678',
      initials: 'L',
      avatarColor: '#3b82f6', // Blue matching screenshot
      assignee: 'Unassigned',
      team: 'Customer Support',
    },
    lastMessage: 'Hey Lucas! Ready for the holiday..',
    timestamp: 'Yesterday',
    unreadCount: 0,
    status: 'open',
    category: 'unassigned',
    team: 'customer_support',
    labels: [],
    notes: [],
    messages: [
      {
        id: 'l1',
        senderId: 9,
        senderName: 'Lucas Green',
        text: 'Hey Lucas! Ready for the holiday campaigns?',
        timestamp: 'Yesterday',
        isMe: false,
      },
    ],
  },
];

export async function fetchConversations(): Promise<Conversation[]> {
  return CONVERSATIONS;
}
